spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        retry:
          initial-interval: 5000

server:
  port: 9093

queue:
  username: rabbitmq
  password: rabbitmq
  auth-exchange-name: auth-exchange
  auth-queue-name: auth-queue
  auth-routing-key: email_notification
  business-exchange-name: business-exchange
  business-queue-name: business-queue
  business-routing-key: create_category_notification

