version: "3.4"

services:
  postgresql:
    image: docker.bintray.io/postgres:9.6.11
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=business_db
      # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000