# Database
datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/business_db
  username: postgres
  password: 123321
# JPA properties
jpa:
  hibernate:
    ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: false